### PR TITLE
Allow importing existing TeamCity groups

### PR DESCRIPTION
**Pull request by justinto-guidewire**

### CODE REVIEW

**Comment by cvbarros** [comment]
Hello @justinto-guidewire, just checking, but have you considered the possibility to use an importer? See example:
https://github.com/cvbarros/terraform-provider-teamcity/blob/master/teamcity/resource_project.go#L17

I believe the API supports querying groups and each individual group, like:
`/app/rest/userGroups/key:ALL_USERS_GROUP`

**Comment by justinto-guidewire** [comment]
Hi @cvbarros, I believe we have the import functionality implemented for the `group` resource, but we were hoping to import existing groups without manually running `terraform import` as we have some complex module structures set up that makes it difficult to import manually...

**Comment by cvbarros** [comment]
Hello @justinto-guidewire,

While I'm empathic to perhaps the struggle to bring in existing resources into Terraform management, at the same time I'd be skeptical of a such change. I'm now aware of such example from other providers (aws, for example) to manage the resource lifecycle via an attribute.

I'm not 100% sure if whether such change would bring value to the "general" use case of the provider, or just to your specific scenario.
Wouldn't it be possible to import the resources following their `module.inner_module.type.resource_name` address, even with the complex module structure?

**Comment by justinto-guidewire** [comment]
Hi @cvbarros, we agree that it's kind of an antipattern to terraform to manage the resource lifecycle via an attribute also, which is why we made this into an optional attribute and the default is set to true.

Another one of our use cases we ran into was for migrating an existing instance of TeamCity using RDS and EBS snapshots, in which case the groups already exist in the snapshot. And the server instance would not be available yet for us to import ahead of time since it hasn't been migrated yet.

**Comment by cvbarros** [comment]
👍

**Pull request merged**
