### PR TITLE
New Data Source/Resource: `teamcity_agent_pool` & `teamcity_agent_pool_project_assignment`

### PR DESCRIPTION
**Pull request by GennadySpb**
Continue of work done by @tombuildsstuff at #80

### CODE REVIEW

**Comment by GennadySpb** [comment]
Kind Up!

**Comment by GennadySpb** [comment]
And up again :)

**Review by cvbarros — APPROVED** [review]

**Comment by cvbarros** [comment]
Thanks for the contribution 💯 🙇 , @GennadySpb 
Sorry for the delay on getting it merged!

Will do a round tonight to publish a new release with the feature 👍

**Comment by GennadySpb** [comment]
@cvbarros Hey-hey! What you think about build & publish release of  **terraform-provider-teamcity**?  :)

**Pull request merged**
